### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Spyntek**
Added build and webconfig artifacts, creatic static-web-app folders

### CODE REVIEW

**Review by Spyntek — COMMENTED** [review]
Approved by code owner

**Comment by MissAlleyCat** [comment]
Commit

**Review by MissAlleyCat — APPROVED** [review]

**Comment by MissAlleyCat** [comment]
Commit

**Comment by thomasgauvin** [comment]
@MissAlleyCat @Spyntek I believe your repositories/PRs are misconfigured and requesting to merge into the official Azure Static Web Apps community repository. Please verify, closing this PR

**Comment by MissAlleyCat** [comment]
approve merge

**Review by MissAlleyCat — COMMENTED** [review]
approve

**Review by MissAlleyCat — COMMENTED** [review]
commit

**Review by MissAlleyCat — COMMENTED** [review]
commit

**Pull request closed without merging**
